var options = {
  'SC01'  : 'Supercharging enabled',
  'DRLH'  : 'Left hand steering wheel',
  'PBSB'  : 'Black paint',
  'PBCW'  : 'White paint',
  'PMSS'  : 'Metallic silver paint',
  'PMMB'  : 'Metallic blue paint',
  'PMSG'  : 'Metallic steel grey paint',
  'PMAB'  : 'Unknown metallic paint',
  'PPMR'  : 'Multi-coat red paint',
  'PPSW'  : 'Multi-coat white paint',
  'RFBK'  : 'Black roof',
  'RFBC'  : 'Roof in body color',
  'RFPO'  : 'Panoramic roof',
  'WT19'  : '19" wheels',
  'WT21'  : '21" wheels',
  'IDPB'  : 'Piano black decor',
  'IDLW'  : 'Lacewood decor',
  'TP02'  : 'Tech package with autopilot',
  'TP00'  : 'No tech package',
  'AU01'  : 'Ultra hifi sound',
  'AU00'  : 'Standard audio',
  'SU01'  : 'Smart air suspension',
  'SU00'  : 'Standard coil suspension',
  'TR01'  : 'Rear facing seats',
  'TR00'  : 'No rear facing seats',
  'CH00'  : 'Single charger',
  'CH01'  : 'Dual charger',
  'SP01'  : 'Safety package',
  'SP00'  : 'Standard alarm',
  'PBT85' : 'P85',
  'COL1'  : 'Solid paint',
  'COL2'  : 'Metallic paint',
  'COL3'  : 'Multi-coat paint',
  'PPSR'  : 'Signature red paint',
  'WTTB'  : '19" Turbine wheels',
  'WTTP'  : 'Unknown wheels',
  'WTSS'  : '21" Silver Turbine wheels',
  'WTSP'  : 'Unknown wheels',
  'WTSG'  : '21" Grey Turbine wheels',
  'QPBT'  : 'Black textile seats',
  'QPMB'  : 'Black leather seats front',
  'QPMG'  : 'Grey leather seats front',
  'QPMT'  : 'Tan leather seats front',
  'QXMB'  : 'Black leather seats back',
  'QXMG'  : 'Grey leather seats back',
  'QXMT'  : 'Tan leather seats back',
  

  'QRLB'  : 'Black next generation seats (front and back)',
  'QRLT'  : 'Tan next generation seats (front and back)',
  'QRLG'  : 'grey next generation seats (front and back)',
  'QNEB'  : 'Black next generation seats (front only)',
  'QNET'  : 'Tan next generation seats (front only)',
  'QNEG'  : 'grey next generation seats (front only)',
  'QNLB'  : 'Black next generation seats (front only)',
  'QNLT'  : 'Tan next generation seats (front only)',
  'QNLG'  : 'grey next generation seats (front only)',
}
